# Generated by Django 5.0.6 on 2024-06-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myfile',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='myfile')),
            ],
        ),
    ]
